# Generated by Django 2.2.5 on 2023-09-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScalableExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(blank=True, db_index=True, editable=False, help_text='When the record has started to be processed, but not yet been completed, only for operational purposes', null=True, verbose_name='Acquired At')),
                ('acquired_by', models.CharField(blank=True, db_index=True, editable=False, help_text='Who has started processing a record but not completed it yet, only for operational purposes', max_length=255, null=True, verbose_name='Acquired By')),
                ('name', models.CharField(help_text='Name of the record to be shown to the user', max_length=128, unique=True, verbose_name='Name')),
                ('processing_timer', models.IntegerField(blank=True, help_text='Processing timer increments every second while processing', null=True, verbose_name='Processing Timer')),
            ],
            options={
                'verbose_name': 'Scalable Example',
                'verbose_name_plural': 'Scalable Examples',
            },
        ),
    ]
